---
title: "Disc_run"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(psych)
library(dplyr)
library(mgc)
library(reshape2)
library(ggplot2)
```


```{r disc, echo=FALSE}
icc_dat <- read.csv('C:/Users/chris/OneDrive - Yale University/NIH/Jupyter notebooks/icc_z_dataframe.csv')

corr_dat <- subset(icc_dat, select = -c(subject, session))
subs <- icc_dat$subject
discr <- discr.test.one_sample(corr_dat, subs)



# node_discr <- rep(0, length(corr_dat))
# for (i in 1:length(corr_dat)) {
#   node_discr[i] <- discr.stat(corr_dat[,c(i)], subs)$discr
#   
#   
# plot(density(node_discr))
# }
```


```{r viz, echo=FALSE}

plot_mtx <- function(Dx, main.title="Distance Matrix", xlab.title="Sample Sorted by Source", ylab.title="Sample Sorted by Source") {
  data <- melt(Dx)
  ggplot(data, aes(x=Var1, y=Var2, fill=value)) +
    geom_tile() +
    scale_fill_gradientn(name="dist(x, y)",
                         colours=c("#f2f0f7", "#cbc9e2", "#9e9ac8", "#6a51a3"),
                         limits=c(min(Dx), max(Dx))) +
    xlab(xlab.title) +
    ylab(ylab.title) +
    theme_bw() +
    ggtitle(main.title)
}


Dx <- as.matrix(dist(corr_dat[sort(subs, index=TRUE)$ix,]), method='euclidian')
plot_mtx(Dx)

```
