---
title: "ICC_run"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(psych)
library(svMisc)
library(dplyr)
library(lme4)
library(readr)

rootdir <- 'C:/Users/chris/OneDrive - Yale University/Projects/ReliabilityAnalysis/'
source('./scripts/icc_run.R')
```

```{r icc, echo=FALSE}
icc_dat <- read_csv(paste0(rootdir,'data/processed/connectivity_data/icc_dataframe.csv'))
icc_dems <- read_csv(paste0(rootdir,'data/processed/connectivity_data/icc_dems.csv'), col_select = c(SDAN, session, Participant_Type2))

icc_dems$subject <- icc_dems$SDAN

mdd <- icc_dems %>% filter(grepl("v1|v4", session)) %>% group_by(subject) %>% filter(length(session) == 2) %>% filter(grepl("v1", session)) %>% ungroup() %>% filter(Participant_Type2 == "MDD")

hv <- icc_dems %>% filter(grepl("v1|v4", session)) %>% group_by(subject) %>% filter(length(session) == 2) %>% filter(grepl("v1", session)) %>% ungroup() %>% filter(Participant_Type2 == "HV")

psych_dat <- get_psych()
mdd_iccs <- run_icc(icc_dat, sublist = mdd$subject, psych_dat = psych_dat, nboot = 10)
write_csv(mdd_iccs, paste0(rootdir,'data/output/mdd_iccs_boot10.csv'))
hv_iccs <- run_icc(icc_dat, sublist = hv$subject)

```

```{r test-parallel}

source('./scripts/icc_bootrun.R')
sublist <- mdd$subject
nboot <- 10
set.seed(1)
bootlist <- replicate(nboot, sample(sublist, length(sublist), replace=T))
bootlist[,1] <- sublist
colnames(bootlist) <- sprintf("%05d", seq(0, 99999))[1:dim(bootlist)[2]]

for(bootn in colnames(bootlist)){
  run_icc(icc_dat, bootlist = bootlist, bootn = bootn, fname = 'icc_mdd')
}
  
```

  
  
```{r icc, echo = FALSE}
iccs_clean <- data.frame()
measure_cols <- colnames(icc_dat)[3:dim(icc_dat)[2]]
has_oy <- icc_dat %>% filter(grepl("v1|v4", session)) %>% group_by(subject) %>% filter(length(session) == 2) %>% filter(grepl("v1", session))
dat <- data.frame()


pb <- txtProgressBar(min = 0, max = length(measure_cols), style = 3)
for(x in measure_cols[1]){
  i <- which(x == measure_cols)
  psych_dat <- read.csv(paste0(rootdir, 'data/processed/connectivity_data/psych_dat/', substring(x,2), '.csv'))
  psych_dat <- merge(psych_dat, has_oy[,c('subject')], by.x = 'X', by.y = 'subject')
  psych_dat$v1 <- apply(psych_dat %>% select(matches("v1")), 1, FUN=function(x){mean(x,na.rm = TRUE)})
  psych_dat$v4 <- apply(psych_dat %>% select(matches("v4")), 1, FUN=function(x){mean(x,na.rm = TRUE)})
  setTxtProgressBar(pb, i)
  Sys.sleep(.01)
  suppressMessages(icc <- ICC(psych_dat[,c("v1","v4")], missing=TRUE,alpha = .05/7381)$results)
  icc$measure <- substring(x,2)
  iccs_clean <- rbind(iccs_clean, icc %>% filter(type == "ICC2"))
}
close(pb)
```

```{r}
iccs_nans <- read.csv('iccs_with_nans.csv')
iccs_f1 <- read.csv('measure_iccs.csv')
cbind(summarise(iccs_nans, Mean = mean(ICC)),summarise(iccs_clean, Mean = mean(ICC)),summarise(iccs_f1, Mean = mean(ICC)))
write.csv(iccs_mdd, 'iccs_mdd.csv')
write.csv(iccs_hv, 'iccs_hv.csv')
```


```{r icc_by_type}
iccs_hv <- data.frame()
measure_cols <- colnames(icc_dat)[3:dim(icc_dat)[2]]

dems <- read.csv('./subs_demographics.csv')
icc_dems <- merge(dems, icc_dat, by.x = c("SDAN","session"), by.y = c("subject", "session"))
has_oy <- icc_dems %>% filter(Participant_Type2 == "HV") %>% filter(grepl("v1|v4", session)) %>% group_by(SDAN) %>% filter(length(session) == 2) %>% filter(grepl("v1", session))


pb <- txtProgressBar(min = 0, max = length(measure_cols), style = 3)
for(x in measure_cols){
  i <- which(x == measure_cols)
  psych_dat <- read.csv(paste0('./psych_dat/', substring(x,2), '.csv'))
  psych_dat <- merge(psych_dat, has_oy[,c('SDAN')], by.x = 'X', by.y = 'SDAN')
  psych_dat$v1 <- apply(psych_dat %>% select(matches("v1")), 1, FUN=function(x){mean(x,na.rm = TRUE)})
  psych_dat$v4 <- apply(psych_dat %>% select(matches("v4")), 1, FUN=function(x){mean(x,na.rm = TRUE)})
  setTxtProgressBar(pb, i)
  Sys.sleep(.01)
  suppressMessages(icc <- ICC(psych_dat[,c("v1","v4")], missing=TRUE,alpha = .05/7381)$results)
  icc$measure <- substring(x,2)
  iccs_hv <- rbind(iccs_hv, icc %>% filter(type == "ICC2"))
}
close(pb)

```




```{python, echo = FALSE}
import pandas as pd
import os

icc_dat = pd.read_csv('C:/Users/chris/OneDrive - Yale University/NIH/Jupyter notebooks/icc_dataframe.csv')
measure_cols = icc_dat.columns[2:]
psych_dat = [None] * len(measure_cols)
psych_dat = [icc_dat.loc[:, ['subject', 'session', mc]].set_index(['subject', 'session'])[mc].unstack() for mc in measure_cols]
```

```{python, echo = FALSE}
mc_res_list = r.mc_res
measure_iccs = pd.DataFrame()
for x in range(len(mc_res_list)):
  mc_res = mc_res_list[x]
  mc_res = mc_res.loc[['Single_random_raters', 'Single_fixed_raters']]
  mc_res['measure'] = measure_cols[x]
  measure_iccs = measure_iccs.append(mc_res)
  if((x+1)%100 == 0):
    print(f'Done {x+1} of {len(mc_res_list)}')
measure_iccs = pd.concat([measure_iccs])
pd.DataFrame(measure_iccs).to_csv('./measure_iccs.csv')
```

```{r, readfile, echo = FALSE}
iccs_mdd = read.csv('./iccs_mdd.csv')
iccs_hv = read.csv('./iccs_hv.csv')

summarise(iccs_mdd, mean(iccs_mdd$ICC), mean(iccs_mdd$lower.bound), mean(iccs_mdd$upper.bound), sd(iccs_mdd$ICC))

summarise(iccs_hv, mean(iccs_hv$ICC), mean(iccs_hv$lower.bound), mean(iccs_hv$upper.bound), sd(iccs_hv$ICC))


summarise(iccs_hv, mean(iccs_mdd$ICC - iccs_hv$ICC),sd(iccs_mdd$ICC - iccs_hv$ICC))
```